# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:           true
  syntax_highlighter: rouge

# Permalinks
permalink:      pretty

# Server
source:         "."
url:            "http://fieldguide.sproutfund.org"
encoding:       UTF-8
exclude:
  - .bundle/
  - .git/
  - .github/
  - _vendor/
  - CODE_OF_CONDUCT.md
  - composer.json
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.md
  - sache.json
  - twbsconfig.yml

plugins:
  - github-pages
  - jekyll-coffeescript
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Github
repository: sproutfund/community-building-field-guide

# Social
title:              "Field Guide for Philanthropy & Civic Action"
description:        "Ideas and resources to seed innovation, make community-advised decisions, host participatory events, communicate effectively, and catalyze local change."
twitter:            sproutfund
authors:            "The Sprout Fund"
social_image_path:  /assets/brand/bootstrap-social.png
social_logo_path:   /assets/brand/bootstrap-social-logo.png

# Custom variables
repo:               "https://github.com/sproutfund/field-guide"
css_sidebar:        "bd-sidebar col-12            col-md-3 col-lg-2 col-xl-2 col-xxl-2                 d-print-none"
css_toc:            "bd-toc     d-none d-lg-block          col-lg-3 col-xl-2 col-xxl-2 ml-auto         d-print-none"
css_main:           "bd-content col-12            col-md-9 col-lg-7 col-xl-7 col-xxl-6 px-md-4 pb-md-4 d-print-block col-print-12 px-print-0 py-print-0"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  bootstrap_css:      "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
  bootstrap_css_hash: "sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
  bootstrap_js:       "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
  bootstrap_js_hash:  "sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
  jquery:             "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  jquery_hash:        "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  popper:             "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  popper_hash:        "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"

relative_links:
  enabled:     true
  collections: false

sass:
  sass_dir: _sass
  style: compressed
